name: Build for Linux and MacOS
on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    strategy:
      matrix:
        include:
          - { os: ubuntu-latest, slug: linux }
          - { os: macos-latest,  slug: darwin }

    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: "1.20.1"

      - name: Install SDL2 on Ubuntu
        run: sudo apt-get install libsdl2{,-image,-mixer,-ttf,-gfx}-dev
        if: matrix.os == 'ubuntu-latest'

      - name: Install SDL2 on MacOS
        run: brew install sdl2{,_image,_mixer,_ttf,_gfx} pkg-config
        if: matrix.os == 'macos-latest'

      - name: Download dependencies
        run: go mod download -x

      - name: Build
        timeout-minutes: 10
        run: |
          mkdir build/
          go build -x -o build/japlay ./cmd/

      - name: Test
        run: go test -v ./... -coverprofile=coverage.txt -covermode=atomic

      - name: Upload coverage to Codecov
        run: bash <(curl -s https://codecov.io/bash)
        if: matrix.os == 'ubuntu-latest'

      - name: Pack files
        run: |
          mkdir -p release/
          tar -cvf release/japlay-${{ matrix.slug }}.tar.gz build/japlay

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: release-${{ matrix.slug }}
          path: release/japlay-${{ matrix.slug }}.tar.gz

  build-windows:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: "1.20.1"

      - name: Install MinGW and SDL2
        run: |
          sudo apt-get install mingw-w64
          wget https://github.com/libsdl-org/SDL/releases/download/release-2.26.3/SDL2-devel-2.26.3-mingw.tar.gz
          tar -xvf SDL2-devel-2.26.3-mingw.tar.gz
          sudo cp -R SDL2-2.26.3/x86_64-w64-mingw32/* /usr/x86_64-w64-mingw32

      - name: Download dependencies
        run: go mod download -x

      - name: Build
        timeout-minutes: 10
        run: |
          mkdir -p build/
          go build -x -o build/japlay.exe ./cmd/

      - name: Test
        run: go test -v ./... -coverprofile=coverage.txt -covermode=atomic

      - name: Pack files
        run: |
          wget https://github.com/libsdl-org/SDL/releases/download/release-2.26.3/SDL2-2.26.3-win32-x64.zip
          unzip SDL2-2.26.3-win32-x64.zip 
          mkdir -p release/
          tar -cvf release/japlay-windows.zip build/japlay.exe SDL2.dll

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: release-windows
          path: release/japlay-windows.zip

  release:
    name: Create Github Release
    needs:
      - build
      - build-windows
    runs-on: ubuntu-latest
    steps:
      - name: Download linux artifacts
        uses: actions/download-artifact@v3
        with:
          name: release-linux
          path: release/japlay-linux.tar.gz

      - name: Download macos artifacts
        uses: actions/download-artifact@v3
        with:
          name: release-darwin
          path: release/japlay-darwin.tar.gz

      - name: Download windows artifacts
        uses: actions/download-artifact@v3
        with:
          name: release-windows
          path: release/japlay-windows.zip

      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            release/japlay-linux.tar.gz
            release/japlay-darwin.tar.gz
            release/japlay-windows.zip
            LICENSE